version: '3.7'
services:
  mongo:
    image: mongo:6.0.5
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017
    volumes:
     - ./mongodb_data_container:/data/db
    command:
      - '--replSet'
      - 'rs0'
      - '--noscripting'
  
  initmongo:
    depends_on:
      - mongo
    image: mongo:6.0.5
    environment:
      - CONN_STR=mongodb://mongo
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"rs.initiate()\" && mongosh $$CONN_STR --eval \"rs.status()\" && mongosh $$CONN_STR --eval \"db.adminCommand({setParameter:1, internalQueryMaxBlockingSortMemoryUsageBytes:2097152000})\"; mongosh $$CONN_STR --eval \"show dbs;\""'

  he:
    depends_on:
     - mongo
    restart: on-failure:3 # 3 retries
    environment:
      - RESTORE_PARTIAL=$RESTORE_PARTIAL
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 5002:5002 # P2P port (if witness needs to talk to other nodes)
    #  - 5003:5003 # RPC port (if node should be available for RPC requests)
    volumes:
      - ./config.json:/hivesmartcontracts/config.json

volumes:
 mongodb_data_container: