services:
  mongo:
    image: mongo:8.0.4
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017
    volumes:
     - ./mongodb_data_container:/data/db
    command:
      - '--replSet'
      - 'rs0'
      - '--noscripting'
  he:
    depends_on:
     - mongo
    restart: on-failure:3 # 3 retries
    environment:
      - RESTORE_PARTIAL=$RESTORE_PARTIAL
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 5002:5002 # P2P port (if witness needs to talk to other nodes)
    #  - 5003:5003 # RPC port (if node should be available for RPC requests)
    volumes:
      - ./config.json:/hivesmartcontracts/config.json

volumes:
 mongodb_data_container:
